# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(default='Dog', max_length=128),
        ),
    ]
